version: "3.8"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dbrootpass
      MYSQL_DATABASE: jetwaydb
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpass
    ports:
      - '3306:3306'
    volumes:
      - /root/jetwaydb/jetway_empty_db.sql:/docker-entrypoint-initdb.d/jetway_empty_db.sql
      - /root/appdata:/var/lib/mysql
  
  jetway-api:
    image: borispdev/jetway-api
    depends_on:
      - db
    container_name: jetway-api
    command: "python main.py"
    environment:
      MYSQL_SERVER: db
      MYSQL_PORT: 3306
      DB_NAME: jetwaydb
      DB_USER: dbuser
      DB_PASSWORD: dbpass
    expose:
      - 8000
  
  jetway-ui:
    image: borispdev/jetway-ui
    container_name: jetway-ui
    environment:
     API_URL: https://api.jet-way.cc
    restart: always
    expose:
      - 3000
  
  jetway-proxy:
    image: borispdev/jetway-proxy
    container_name: jetway-proxy
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /proxy/ssl:/etc/nginx/ssl